<<<<<<< HEAD
// AUTH
export const LOGGED = 'LOGGED'
export const USER = 'USER'

// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'

// USERS
export const SELECTED_USER = 'SELECTED_USER'
export const SET_USERS = 'SET_USERS'
=======
// AUTH
export const LOGGED = 'LOGGED'
export const USER = 'USER'

// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'

// USERS
export const SELECTED_USER = 'SELECTED_USER'
export const SET_USERS = 'SET_USERS'
>>>>>>> 6de1edbfff1a6c6b67eaaada20d9102f6d002303
